@Pizzeria_HostAddress = http://localhost:5205

GET {{Pizzeria_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{Pizzeria_HostAddress}}/auth/login/
Accept: application/json

email=


